## Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.

You have the following three operations permitted on a word: Insert a character,Delete a character,Replace a character

In [1]:
import numpy as np
def minDistance(string1,string2): 
    numChars1 = len(string1)
    numChars2 = len(string2)
    dataMatrix = np.zeros((numChars1,numChars2)) #matrix to store previously evaluated substrings. 
    dataMatrix [:, 0] = np.linspace(0, numChars1-1, num=numChars1)#initialize data matrix
    dataMatrix [0, :] = np.linspace(0, numChars2-1, num=numChars2)
        
    for i in range(1, numChars1):
        for j in range(1, numChars2):
            if string1[i-1] == string2[j-1]: #basic algorithm to populate data matrix. 
                dataMatrix [i,j] = min(dataMatrix[i-1, j] + 1,dataMatrix[i-1, j-1],dataMatrix[i, j-1] + 1)
            else:
                dataMatrix [i,j] = min(dataMatrix[i-1,j] + 1,dataMatrix[i-1,j-1] + 1,dataMatrix[i,j-1] + 1)
                
    print (dataMatrix)
    return (dataMatrix[numChars1 - 1, numChars2 - 1]) # location where the solution is present.  
minDistance('hello','hello')

[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 0. 1.]
 [4. 3. 2. 1. 0.]]


0.0

In [2]:
minDistance('hello','jello')

[[0. 1. 2. 3. 4.]
 [1. 1. 2. 3. 4.]
 [2. 2. 1. 2. 3.]
 [3. 3. 2. 1. 2.]
 [4. 4. 3. 2. 1.]]


1.0

In [3]:
minDistance('LeBron James','Michael Jordan')

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 1.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 2.  2.  2.  3.  4.  5.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 3.  3.  3.  3.  4.  5.  6.  6.  7.  8.  9. 10. 11. 12.]
 [ 4.  4.  4.  4.  4.  5.  6.  7.  7.  8.  9.  9. 10. 11.]
 [ 5.  5.  5.  5.  5.  5.  6.  7.  8.  8.  8.  9. 10. 11.]
 [ 6.  6.  6.  6.  6.  6.  6.  7.  8.  9.  9.  9. 10. 11.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  9. 10. 10. 11.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  8.  7.  8.  9. 10. 11.]
 [ 9.  9.  9.  9.  9.  8.  9.  9.  9.  8.  8.  9. 10. 10.]
 [10. 10. 10. 10. 10.  9.  9. 10. 10.  9.  9.  9. 10. 11.]
 [11. 11. 11. 11. 11. 10.  9. 10. 11. 10. 10. 10. 10. 11.]]


11.0